2024-05-13 09:27:16,889 : INFO : root : Loading config.
2024-05-13 09:27:16,891 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-05-13 09:27:16,891 : INFO : ConfigProcessor : Loading config from cache: /tmp/a1ac3a016f6424d80551e58412719826.mpf_cache
2024-05-13 09:27:16,918 : INFO : ConfigProcessor : Loading config from cache: /tmp/d2309f45f00263c22cb8c5b4ec4cc881.mpf_cache
2024-05-13 09:27:16,918 : INFO : ConfigProcessor : Loading config from cache: /tmp/7559345efe69122f4d6fb5f65214b482.mpf_cache
2024-05-13 09:27:16,918 : WARNING : ConfigProcessor : Config file in cache changed: /home/mpfuser/pinball/Futurama337/modes/base/config/base.yaml
2024-05-13 09:27:16,918 : INFO : ConfigProcessor : Loading config from file /home/mpfuser/pinball/Futurama337/modes/base/config/base.yaml.
2024-05-13 09:27:16,974 : INFO : ConfigProcessor : Loading config: /home/mpfuser/pinball/Futurama337/modes/base/config/base.yaml
2024-05-13 09:27:16,975 : INFO : ConfigProcessor : Config file cache created: /tmp/1705bafe70d7ed166ffa6fbc6eff32b6.mpf_cache
2024-05-13 09:27:16,975 : INFO : ConfigProcessor : Loading config from cache: /tmp/f4afb52e5a81c0586c038bffbccda3a8.mpf_cache
2024-05-13 09:27:16,976 : INFO : ConfigProcessor : Loading config from cache: /tmp/e673d636849e9b65d988aeeaedcc2308.mpf_cache
2024-05-13 09:27:16,976 : INFO : ConfigProcessor : Loading config from cache: /tmp/1fd3fa5a2a3cce4d2f903ebd1f33b613.mpf_cache
2024-05-13 09:27:16,976 : INFO : ConfigProcessor : Loading config from cache: /tmp/443b0f17029558a07eb16f1a5797ce25.mpf_cache
2024-05-13 09:27:16,976 : INFO : ConfigProcessor : Loading config from cache: /tmp/2eca5affb57b5e78fb2953eb996a3c84.mpf_cache
2024-05-13 09:27:16,976 : INFO : ConfigProcessor : Loading config from cache: /tmp/1addde10c9588a5a3f6d737fdd11a11e.mpf_cache
2024-05-13 09:27:16,977 : INFO : ConfigProcessor : Loading config from cache: /tmp/1876950c274b9e7ea6a8c45d76a940cb.mpf_cache
2024-05-13 09:27:16,977 : INFO : ConfigProcessor : Loading config from cache: /tmp/8f7509494fc9fc6e1004eca749828db1.mpf_cache
2024-05-13 09:27:16,977 : INFO : ConfigProcessor : Loading config from cache: /tmp/cefc2bc6f058ed166b4a689d4941d80b.mpf_cache
2024-05-13 09:27:16,977 : INFO : ConfigProcessor : Loading config from cache: /tmp/41a5583746daef48401a23ecf1a259ba.mpf_cache
2024-05-13 09:27:16,977 : INFO : ConfigProcessor : Loading config from cache: /tmp/b23f0d2198bd0eb0d6e1b1a9a4c546b0.mpf_cache
2024-05-13 09:27:16,977 : INFO : ConfigProcessor : Loading config from cache: /tmp/8b80e358850df47ca9876a78861d2157.mpf_cache
2024-05-13 09:27:16,978 : INFO : Machine : Mission Pinball Framework Core Engine v0.55.0
2024-05-13 09:27:16,978 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'jsonlogging': False, 'logfile': 'logs/2024-05-13-09-27-16-mpf-futurama.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2024-05-13 09:27:16,978 : INFO : Machine : MPF path: /usr/local/lib/python3.7/dist-packages/mpf
2024-05-13 09:27:16,978 : INFO : Machine : Machine path: /home/mpfuser/pinball/Futurama337
2024-05-13 09:27:16,978 : INFO : Machine : Platform: linux
2024-05-13 09:27:16,978 : INFO : Machine : Python executable location: /usr/bin/python3
2024-05-13 09:27:16,978 : INFO : Machine : Python version: 3.7.3 (64-bit)
2024-05-13 09:27:16,979 : INFO : Machine : Initialise MPF.
2024-05-13 09:27:17,005 : INFO : P-Roc : Connecting to P-ROC
2024-05-13 09:27:17,058 : INFO : P-Roc : Successfully connected to P-ROC/P3-ROC. Firmware Version: 2. Firmware Revision: 14. Hardware Board ID: 1
2024-05-13 09:27:17,066 : INFO : EventManager : Event: ======'machine_var_p_roc_version'====== Args={'value': 2, 'prev_value': None, 'change': True}
2024-05-13 09:27:17,066 : INFO : EventManager : Event: ======'machine_var_p_roc_revision'====== Args={'value': 14, 'prev_value': None, 'change': True}
2024-05-13 09:27:17,066 : INFO : EventManager : Event: ======'machine_var_p_roc_hardware_version'====== Args={'value': 1, 'prev_value': None, 'change': True}
2024-05-13 09:27:17,066 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2024-05-13 09:27:17,091 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.9, 'prev_value': None, 'change': True}
2024-05-13 09:27:17,091 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 3376, 'prev_value': None, 'change': True}
2024-05-13 09:27:17,091 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'MPF v0.55.0', 'prev_value': None, 'change': True}
2024-05-13 09:27:17,091 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'MPF v0.55.0, Config version:5, Show version: 5, BCP version:1.1', 'prev_value': None, 'change': True}
2024-05-13 09:27:17,091 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.7.3', 'prev_value': None, 'change': True}
2024-05-13 09:27:17,092 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Linux-4.19.0-20-amd64-x86_64-with-debian-10.12', 'prev_value': None, 'change': True}
2024-05-13 09:27:17,092 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Linux', 'prev_value': None, 'change': True}
2024-05-13 09:27:17,092 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '4.19.0-20-amd64', 'prev_value': None, 'change': True}
2024-05-13 09:27:17,092 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '#1 SMP Debian 4.19.235-1 (2022-03-17)', 'prev_value': None, 'change': True}
2024-05-13 09:27:17,092 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'x86_64', 'prev_value': None, 'change': True}
2024-05-13 09:27:17,092 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2024-05-13 09:27:17,124 : INFO : EventManager : Event: ======'drop_target_bank_crew_bank_up'====== Args={}
2024-05-13 09:27:17,147 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2024-05-13 09:27:17,163 : INFO : SwitchController : Found active switch: (30, <Platform.P3-ROC>) <switch.s_trough1>
2024-05-13 09:27:17,163 : INFO : SwitchController : Found active switch: (28, <Platform.P3-ROC>) <switch.s_pe_platter>
2024-05-13 09:27:17,172 : ERROR : ConfigValidator : Your config contains a value for the setting "sound_player:loop", but this is not a valid setting name.
2024-05-13 09:27:17,172 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...tting name.')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...tting name.')>)>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/events.py", line 728, in _queue_task_done
    future.result()
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/events.py", line 645, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/mode_controller.py", line 101, in initialise_modes
    **item.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_player.py", line 132, in process_mode_config
    config = self.validate_config(config)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_player.py", line 104, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "/usr/local/lib/python3.7/dist-packages/mpf/config_players/device_config_player.py", line 56, in validate_config_entry
    raise e
  File "/usr/local/lib/python3.7/dist-packages/mpf/config_players/device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "/usr/local/lib/python3.7/dist-packages/mpf/config_players/device_config_player.py", line 79, in _validate_config_item
    device_settings = self._parse_config(device_settings, device)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_player.py", line 126, in _parse_config
    return self.get_full_config(config)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_player.py", line 199, in get_full_config
    self.config_file_section, value, base_spec='config_player_common')
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_validator.py", line 180, in validate_config
    validation_failure_info=validation_failure_info)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_validator.py", line 192, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_validator.py", line 359, in check_for_invalid_sections
    'setting name.', 2, self.log.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Failed to load config player s_mag_button_active:sounds with settings {'hypnotoad_short': {'loop': -1}} >> Your config contains a value for the setting "sound_player:loop", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://docs.missionpinball.org/en/0.55/logs/CFE-ConfigValidator-2.html)
2024-05-13 09:27:17,175 : INFO : Machine : Starting the main run loop.
2024-05-13 09:27:17,176 : INFO : Machine : Shutting down...
2024-05-13 09:27:17,176 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-05-13 09:27:17,253 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/machine.py", line 769, in _run_loop
    raise self._exception['exception']
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/events.py", line 728, in _queue_task_done
    future.result()
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/events.py", line 645, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/mode_controller.py", line 101, in initialise_modes
    **item.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_player.py", line 132, in process_mode_config
    config = self.validate_config(config)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_player.py", line 104, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "/usr/local/lib/python3.7/dist-packages/mpf/config_players/device_config_player.py", line 56, in validate_config_entry
    raise e
  File "/usr/local/lib/python3.7/dist-packages/mpf/config_players/device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "/usr/local/lib/python3.7/dist-packages/mpf/config_players/device_config_player.py", line 79, in _validate_config_item
    device_settings = self._parse_config(device_settings, device)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_player.py", line 126, in _parse_config
    return self.get_full_config(config)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_player.py", line 199, in get_full_config
    self.config_file_section, value, base_spec='config_player_common')
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_validator.py", line 180, in validate_config
    validation_failure_info=validation_failure_info)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_validator.py", line 192, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "/usr/local/lib/python3.7/dist-packages/mpf/core/config_validator.py", line 359, in check_for_invalid_sections
    'setting name.', 2, self.log.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Failed to load config player s_mag_button_active:sounds with settings {'hypnotoad_short': {'loop': -1}} >> Your config contains a value for the setting "sound_player:loop", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://docs.missionpinball.org/en/0.55/logs/CFE-ConfigValidator-2.html)
